---
gitlab_external_host: "${gitlab_external_host}"
gitlab_external_url: "${gitlab_external_protocol}://${gitlab_external_host}"
gitlab_data_mountpoint: "${gitlab_data_mountpoint}"
gitlab_db_name: "${gitlab_db_name}"
gitlab_db_username: "${gitlab_db_username}"
gitlab_db_password: "${gitlab_db_password}"
gitlab_root_password: "${gitlab_root_password}"
gitlab_ci_registration_token: "${gitlab_ci_registration_token}"
gitlab_db_host: "${gitlab_db_host}"
gitlab_db_port: ${gitlab_db_port}
gitlab_cache_host: "${gitlab_cache_host}"
gitlab_cache_port: ${gitlab_cache_port}
gitlab_proxy_subnets:
  - "${gitlab_proxy_subnet1}"
  - "${gitlab_proxy_subnet2}"
ldap_host_name: "${ldap_host_name}"
ldap_bind_dn: "${ldap_bind_dn}"
ldap_password: "${ldap_password}"
ldap_base: "${ldap_base}"